services:
  - type: web
    name: mbbswala-backend-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: SUPABASE_URL
        value: https://afrrwsxuznkyewkndzff.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_5D517PLNdF92v3Q1s6Dp_w_WaZtsrPo
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: sb_publishable_5D517PLNdF92v3Q1s6Dp_w_WaZtsrPo
      - key: SCRAPER_CONCURRENCY
        value: 3
