/**
 * State Counselling Authorities Registry
 * 
 * Maps official medical counselling authorities across all 36 States & Union Territories of India.
 * Pluggable architecture allowing new authorities and endpoints to be added declaratively.
 */

export interface StateAuthorityConfig {
  code: string;
  state: string;
  name: string;
  baseUrl: string;
  noticePages: string[];
  courses: ('MBBS' | 'BDS' | 'BAMS' | 'BHMS' | 'BUMS' | 'BSMS' | 'BNYS')[];
  enabled: boolean;
  priority: number; // 1 (highest) to 5 (lowest)
  counsellingBodyType: 'DME' | 'CET_CELL' | 'UNIVERSITY' | 'BOARD' | 'DGME' | 'DIRECTORATE' | 'COMMISSION' | 'COMMITTEE';
}

export const STATE_AUTHORITIES: StateAuthorityConfig[] = [
  // ── Central & Northern States ──────────────────────────────────────────────
  {
    code: 'DME_MP',
    state: 'Madhya Pradesh',
    name: 'Directorate of Medical Education (DME MP)',
    baseUrl: 'https://dme.mponline.gov.in',
    noticePages: ['/', '/portal/services/dme-ug/counselling.aspx', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DGME_UP',
    state: 'Uttar Pradesh',
    name: 'Directorate General of Medical Education and Training (DGME UP)',
    baseUrl: 'https://upneet.gov.in',
    noticePages: ['/', '/notices', '/downloads'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'DGME',
  },
  {
    code: 'RUHS_RAJ',
    state: 'Rajasthan',
    name: 'Rajasthan NEET UG Medical & Dental Counselling Board',
    baseUrl: 'https://rajneetug.org',
    noticePages: ['/', '/notifications', '/downloads'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'CET_MAH',
    state: 'Maharashtra',
    name: 'State Common Entrance Test Cell, Maharashtra',
    baseUrl: 'https://cetcell.mahacet.org',
    noticePages: ['/CAP-landing-page-2026/', '/CAP-landing-page-2025/', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS', 'BNYS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'CET_CELL',
  },
  {
    code: 'KEA_KAR',
    state: 'Karnataka',
    name: 'Karnataka Examinations Authority (KEA)',
    baseUrl: 'https://cetonline.karnataka.gov.in/kea',
    noticePages: ['/ugneet2026', '/ugneet2025', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS', 'BNYS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'CET_CELL',
  },
  {
    code: 'ACPUGMEC_GUJ',
    state: 'Gujarat',
    name: 'Admission Committee for Professional Undergraduate Medical Educational Courses (ACPUGMEC)',
    baseUrl: 'https://www.medadmgujarat.org',
    noticePages: ['/ug/home.aspx', '/notices', '/downloads'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'BCECEB_BIH',
    state: 'Bihar',
    name: 'Bihar Combined Entrance Competitive Examination Board (BCECEB - UGMAC)',
    baseUrl: 'https://bceceboard.bihar.gov.in',
    noticePages: ['/', '/UGMAC_adv.php', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'DME_TN',
    state: 'Tamil Nadu',
    name: 'Directorate of Medical Education and Research, Tamil Nadu',
    baseUrl: 'https://tnmedicalselection.net',
    noticePages: ['/ug.aspx', '/notices.aspx', '/'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BSMS', 'BNYS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'DME',
  },
  {
    code: 'CEE_KER',
    state: 'Kerala',
    name: 'Commissioner for Entrance Examinations (CEE Kerala - KEAM)',
    baseUrl: 'https://cee.kerala.gov.in',
    noticePages: ['/keam2026', '/keam2025', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BSMS'],
    enabled: true,
    priority: 1,
    counsellingBodyType: 'CET_CELL',
  },
  {
    code: 'IPU_DELHI',
    state: 'Delhi',
    name: 'Guru Gobind Singh Indraprastha University (GGSIPU / DU / IPU)',
    baseUrl: 'http://www.ipu.ac.in',
    noticePages: ['/notices.php', '/admissions.php'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'KNRUHS_TEL',
    state: 'Telangana',
    name: 'Kaloji Narayana Rao University of Health Sciences (KNRUHS)',
    baseUrl: 'https://www.knruhs.telangana.gov.in',
    noticePages: ['/notifications/', '/admissions/'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'YSRUHS_AP',
    state: 'Andhra Pradesh',
    name: 'Dr. YSR University of Health Sciences (YSRUHS)',
    baseUrl: 'https://drysruhs.edu.in',
    noticePages: ['/notifications.html', '/admissions.html'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'WBMCC_WB',
    state: 'West Bengal',
    name: 'West Bengal Medical Counselling Committee (WBMCC)',
    baseUrl: 'https://wbmcc.nic.in',
    noticePages: ['/ug-counselling', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BUMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'DME',
  },
  {
    code: 'BFUHS_PUN',
    state: 'Punjab',
    name: 'Baba Farid University of Health Sciences (BFUHS)',
    baseUrl: 'https://bfuhs.ac.in',
    noticePages: ['/web/UGMedical/ugmedical.asp', '/notifications.asp'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'DMER_HAR',
    state: 'Haryana',
    name: 'Directorate of Medical Education and Research, Haryana / UHSR',
    baseUrl: 'https://dmer.haryana.gov.in',
    noticePages: ['/notices', '/counselling'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'DME',
  },
  {
    code: 'OJEE_ODI',
    state: 'Odisha',
    name: 'Odisha Joint Entrance Examination (OJEE Medical Counselling)',
    baseUrl: 'https://ojee.nic.in',
    noticePages: ['/medical-counselling/', '/notices/'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'DME_CG',
    state: 'Chhattisgarh',
    name: 'Directorate of Medical Education, Chhattisgarh (CGDME)',
    baseUrl: 'https://cgdme.in',
    noticePages: ['/notices', '/ug-counselling'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'DME',
  },
  {
    code: 'JCECEB_JHA',
    state: 'Jharkhand',
    name: 'Jharkhand Combined Entrance Competitive Examination Board (JCECEB)',
    baseUrl: 'https://jceceb.jharkhand.gov.in',
    noticePages: ['/notices', '/admissions'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 2,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'DME_ASM',
    state: 'Assam',
    name: 'Directorate of Medical Education, Assam',
    baseUrl: 'https://dme.assam.gov.in',
    noticePages: ['/documents/notices', '/latest-updates'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'DME',
  },
  {
    code: 'HNBUMU_UK',
    state: 'Uttarakhand',
    name: 'Hemwati Nandan Bahuguna Uttarakhand Medical Education University',
    baseUrl: 'https://hnbumu.ac.in',
    noticePages: ['/neet-ug-counselling', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'AMRU_HP',
    state: 'Himachal Pradesh',
    name: 'Atal Medical and Research University (AMRU HP)',
    baseUrl: 'https://amruhp.ac.in',
    noticePages: ['/neet-ug-counselling/', '/notifications/'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'UNIVERSITY',
  },
  {
    code: 'JKBOPEE_JK',
    state: 'Jammu & Kashmir',
    name: 'J&K Board of Professional Entrance Examinations (BOPEE)',
    baseUrl: 'https://jkbopee.gov.in',
    noticePages: ['/Notifications.aspx', '/Home.aspx'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BUMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'DTE_GOA',
    state: 'Goa',
    name: 'Directorate of Technical Education, Goa (DTE Goa)',
    baseUrl: 'https://dte.goa.gov.in',
    noticePages: ['/admissions', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DME_TRIPURA',
    state: 'Tripura',
    name: 'Directorate of Medical Education, Tripura',
    baseUrl: 'https://dme.tripura.gov.in',
    noticePages: ['/notifications', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'DME',
  },
  {
    code: 'CENTAC_PUDU',
    state: 'Puducherry',
    name: 'Centralised Admission Committee (CENTAC Puducherry)',
    baseUrl: 'https://centacpuducherry.in',
    noticePages: ['/ug-neet', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'BOARD',
  },
  {
    code: 'GMCH_CHD',
    state: 'Chandigarh',
    name: 'Government Medical College & Hospital (GMCH Chandigarh)',
    baseUrl: 'https://gmch.gov.in',
    noticePages: ['/admissions', '/notices'],
    courses: ['MBBS', 'BDS', 'BHMS'],
    enabled: true,
    priority: 3,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DME_MEG',
    state: 'Meghalaya',
    name: 'Department of Health & Family Welfare, Meghalaya',
    baseUrl: 'https://meghealth.gov.in',
    noticePages: ['/notifications.html', '/notices.html'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DTE_MAN',
    state: 'Manipur',
    name: 'Directorate of Health Services, Manipur',
    baseUrl: 'https://manipurhealthdirectorate.mn.gov.in',
    noticePages: ['/notifications', '/counselling'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHE_MIZ',
    state: 'Mizoram',
    name: 'Higher & Technical Education Department, Mizoram',
    baseUrl: 'https://dhte.mizoram.gov.in',
    noticePages: ['/notice', '/notifications'],
    courses: ['MBBS', 'BDS', 'BAMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DTE_NAG',
    state: 'Nagaland',
    name: 'Directorate of Technical Education, Nagaland',
    baseUrl: 'https://dtenagaland.org.in',
    noticePages: ['/notifications', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHE_ARU',
    state: 'Arunachal Pradesh',
    name: 'Directorate of Higher & Technical Education, Arunachal Pradesh',
    baseUrl: 'https://apdhte.nic.in',
    noticePages: ['/notifications.html', '/notices.html'],
    courses: ['MBBS', 'BDS', 'BAMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHE_SIK',
    state: 'Sikkim',
    name: 'Education Department, Government of Sikkim',
    baseUrl: 'https://sikkim.gov.in',
    noticePages: ['/notices', '/notifications'],
    courses: ['MBBS', 'BDS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHS_ANDAMAN',
    state: 'Andaman & Nicobar Islands',
    name: 'Directorate of Health Services, Andaman & Nicobar',
    baseUrl: 'https://dhs.andaman.gov.in',
    noticePages: ['/notices', '/admissions'],
    courses: ['MBBS', 'BDS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHS_DNHD',
    state: 'Dadra & Nagar Haveli and Daman & Diu',
    name: 'Directorate of Medical & Health Services, DNH & DD',
    baseUrl: 'https://daman.nic.in',
    noticePages: ['/health-services/admissions', '/notices'],
    courses: ['MBBS', 'BDS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHS_LAK',
    state: 'Lakshadweep',
    name: 'Department of Health Services, UT of Lakshadweep',
    baseUrl: 'https://lakshadweep.gov.in',
    noticePages: ['/notices', '/notifications'],
    courses: ['MBBS', 'BDS', 'BAMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
  {
    code: 'DHS_LADAKH',
    state: 'Ladakh',
    name: 'Administration of Union Territory of Ladakh',
    baseUrl: 'https://ladakh.gov.in',
    noticePages: ['/notifications', '/notices'],
    courses: ['MBBS', 'BDS', 'BAMS'],
    enabled: true,
    priority: 4,
    counsellingBodyType: 'DME',
  },
];

/**
 * Registry Helper Functions
 */
export function getAllStateAuthorities(): StateAuthorityConfig[] {
  return STATE_AUTHORITIES.filter((a) => a.enabled);
}

export function getStateAuthorityByCode(code: string): StateAuthorityConfig | undefined {
  return STATE_AUTHORITIES.find((a) => a.code.toUpperCase() === code.toUpperCase());
}

export function getStateAuthorityByState(stateName: string): StateAuthorityConfig | undefined {
  const norm = stateName.trim().toLowerCase();
  return STATE_AUTHORITIES.find((a) => a.state.toLowerCase() === norm);
}

export function getHighPriorityStateAuthorities(): StateAuthorityConfig[] {
  return STATE_AUTHORITIES.filter((a) => a.enabled && a.priority <= 2);
}
