-- Withdrawals schema
CREATE TABLE IF NOT EXISTS withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    amount NUMERIC(10,2) NOT NULL,
    method TEXT NOT NULL,
    account_detail TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    remarks TEXT DEFAULT '',
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;

-- Users can read their own withdrawals
CREATE POLICY "Users can read own withdrawals" 
ON withdrawals FOR SELECT 
USING (auth.uid() = user_id);

-- Users can insert their own withdrawals
CREATE POLICY "Users can insert own withdrawals" 
ON withdrawals FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Only admins can update (handled via server bypass since we use service role or direct API)
CREATE POLICY "Admins can update withdrawals" 
ON withdrawals FOR UPDATE 
USING (
    EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() 
        AND role IN ('admin', 'super_admin')
    )
);

CREATE POLICY "Admins can read all withdrawals" 
ON withdrawals FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() 
        AND role IN ('admin', 'super_admin')
    )
);
